export const newsFeed = {
  SET_NEWS_FEED: 'SET_NEWS_FEED',
  SET_IS_ARTICLE_LOADING: 'SET_IS_ARTICLE_LOADING',
  SET_IS_COMMENT_LOADING: 'SET_IS_COMMENT_LOADING',
  SET_COMMENTS: 'SET_COMMENTS',
  UPDATE_ARTILCE_PAGINATION: 'UPDATE_ARTILCE_PAGINATION',
  SAVED_ARTICLES_LOADING: 'SAVED_ARTICLES_LOADING',
  SET_SAVED_ARTICLES: 'SET_SAVED_ARTICLES',
};
